"""Remove empty field

Revision ID: a87c3c86f429
Revises: bf7fe87e5dfb
Create Date: 2019-05-03 10:13:57.504198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a87c3c86f429'
down_revision = 'bf7fe87e5dfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'empty')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('empty', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
