"""Add technologies

Revision ID: b7ca974cb6fc
Revises: db8dd2ab30b8
Create Date: 2019-05-02 10:25:01.980567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7ca974cb6fc'
down_revision = 'db8dd2ab30b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('technlologies', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'technlologies')
    # ### end Alembic commands ###
