"""Initial Migration

Revision ID: bf7fe87e5dfb
Revises: c89ca5c77766
Create Date: 2019-05-03 10:13:17.025006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf7fe87e5dfb'
down_revision = 'c89ca5c77766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('empty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'empty')
    # ### end Alembic commands ###
