"""Rename technologies

Revision ID: c89ca5c77766
Revises: b7ca974cb6fc
Create Date: 2019-05-02 10:26:13.892790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c89ca5c77766'
down_revision = 'b7ca974cb6fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('technologies', sa.String(), nullable=True))
    op.drop_column('pitches', 'technlologies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('technlologies', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('pitches', 'technologies')
    # ### end Alembic commands ###
